/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobilecenter.pkg8;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Chanda Jaiswal
 */
public class MobileCenterBillInfo extends javax.swing.JFrame {

    /**
     * Creates new form MobileCenterBillInfo
     */
    public MobileCenterBillInfo() {
        initComponents();
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        billLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        addLbl = new javax.swing.JLabel();
        billBrandLbl = new javax.swing.JLabel();
        billModelLbl = new javax.swing.JLabel();
        billPriceLbl = new javax.swing.JLabel();
        billQtyLbl = new javax.swing.JLabel();
        addTxtFld = new javax.swing.JTextField();
        billBrandTxtFld = new javax.swing.JTextField();
        billModelTxtFld = new javax.swing.JTextField();
        billPriceTxtFld = new javax.swing.JTextField();
        billScrollPane = new javax.swing.JScrollPane();
        billTextArea = new javax.swing.JTextArea();
        billGenBtn = new javax.swing.JButton();
        billclearBtn = new javax.swing.JButton();
        billClearBtn = new javax.swing.JButton();
        billBackBtn = new javax.swing.JButton();
        TotalLbl = new javax.swing.JLabel();
        TotalTxtFld = new javax.swing.JTextField();
        qtySpin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(84, 124, 134));

        billLbl.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        billLbl.setForeground(new java.awt.Color(255, 255, 255));
        billLbl.setText("Mobile Center Information System");

        nameLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setText("          Name :");

        addLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        addLbl.setForeground(new java.awt.Color(255, 255, 255));
        addLbl.setText("      Address :");

        billBrandLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        billBrandLbl.setForeground(new java.awt.Color(255, 255, 255));
        billBrandLbl.setText("      Brand Name :");

        billModelLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        billModelLbl.setForeground(new java.awt.Color(255, 255, 255));
        billModelLbl.setText("      Model Name :");

        billPriceLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        billPriceLbl.setForeground(new java.awt.Color(255, 255, 255));
        billPriceLbl.setText("                  Price :");

        billQtyLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        billQtyLbl.setForeground(new java.awt.Color(255, 255, 255));
        billQtyLbl.setText("             Quantity :");

        billTextArea.setColumns(20);
        billTextArea.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        billTextArea.setRows(5);
        billScrollPane.setViewportView(billTextArea);

        billGenBtn.setBackground(new java.awt.Color(255, 255, 255));
        billGenBtn.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        billGenBtn.setText("GENERATE BILL");
        billGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billGenBtnActionPerformed(evt);
            }
        });

        billclearBtn.setBackground(new java.awt.Color(255, 255, 255));
        billclearBtn.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        billclearBtn.setText("CLEAR BILL");
        billclearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billclearBtnActionPerformed(evt);
            }
        });

        billClearBtn.setBackground(new java.awt.Color(255, 255, 255));
        billClearBtn.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        billClearBtn.setText("CLEAR");
        billClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billClearBtnActionPerformed(evt);
            }
        });

        billBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        billBackBtn.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        billBackBtn.setText("BACK");
        billBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBackBtnActionPerformed(evt);
            }
        });

        TotalLbl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        TotalLbl.setForeground(new java.awt.Color(255, 255, 255));
        TotalLbl.setText("                  Total :");

        qtySpin.setModel(new javax.swing.SpinnerNumberModel());
        qtySpin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtySpinStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(billClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billGenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(billclearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(billBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billBrandLbl)
                            .addComponent(addLbl)
                            .addComponent(nameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTxtFld)
                            .addComponent(billBrandTxtFld)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billQtyLbl)
                            .addComponent(billPriceLbl)
                            .addComponent(billModelLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billModelTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billPriceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtySpin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TotalLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TotalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(billScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billLbl)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billLbl)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(billScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLbl)
                            .addComponent(addTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billBrandLbl)
                            .addComponent(billBrandTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billModelLbl)
                            .addComponent(billModelTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billPriceLbl)
                            .addComponent(billPriceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billQtyLbl)
                            .addComponent(qtySpin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalLbl)
                            .addComponent(TotalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billclearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBackBtnActionPerformed
        // TODO add your handling code here:
        close();
        MobileCenterInfo mobileinfo = new MobileCenterInfo();
        mobileinfo.setVisible(true);
        
    }//GEN-LAST:event_billBackBtnActionPerformed

    private void billGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billGenBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxtFld.getText().toString();
        String address = addTxtFld.getText().toString();
        String BrandName = billBrandTxtFld.getText().toString();
        String ModelName = billModelTxtFld.getText().toString();
        String Quantity = qtySpin.getValue().toString();
        String Price = billPriceTxtFld.getText().toString();
        String Total = TotalTxtFld.getText().toString();
        
        if(name.equals("") && address.equals("") && BrandName.equals("") && ModelName.equals("") && Quantity.equals(0) &&  Price.equals("") && Total.equals("")){
            JOptionPane.showMessageDialog(null,"Empty Fields Found !!");
         
        }
        
        else{
    
        
            billTextArea.append("\n\t Mobile Center Information System \n\n" +
                "\t                Purchase Receipt \t\t\t"+
                "\n\n\n----------------------------------------------------------------------------------------\n"+
                "Customer Name:\t"+nameTxtFld.getText()+"\n\n"+
                "Address:\t\t"+addTxtFld.getText()+"\n"+
                "----------------------------------------------------------------------------------------\n"+
                " Brand Name | "+"      Model Name | "+"      Quantity | "+"      Price "+"\n"+
                "  "+billBrandTxtFld.getText()+" \t "+
                "   "+billModelTxtFld.getText()+" \t   "+
                "     "+qtySpin.getValue()+" \t "+
                "     "+billPriceTxtFld.getText()+" \t "+"\n\n\n"+
                " \t\t\t Total:  "+TotalTxtFld.getText()+"\n\n"+
                "----------------------------------Thank You For Visiting!!--------------------------\n"
                   
                
        
        
        
        
       
        
        
           );
        }
        
        
    }//GEN-LAST:event_billGenBtnActionPerformed

    private void qtySpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtySpinStateChanged
        // TODO add your handling code here:
        int quantity = Integer.parseInt(qtySpin.getValue().toString());
        int price = Integer.parseInt(billPriceTxtFld.getText());
        
        int total  = quantity * price;
        
        TotalTxtFld.setText(String.valueOf(total));
    }//GEN-LAST:event_qtySpinStateChanged

    private void billClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billClearBtnActionPerformed
        // TODO add your handling code here:
        nameTxtFld.setText("");
        addTxtFld.setText("");
        billBrandTxtFld.setText("");
        billModelTxtFld.setText("");
        qtySpin.setValue(0);
        billPriceTxtFld.setText("");
        TotalTxtFld.setText("");
    }//GEN-LAST:event_billClearBtnActionPerformed

    private void billclearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billclearBtnActionPerformed
        // TODO add your handling code here:
        billTextArea.setText("");
    }//GEN-LAST:event_billclearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileCenterBillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileCenterBillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileCenterBillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileCenterBillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileCenterBillInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalLbl;
    private javax.swing.JTextField TotalTxtFld;
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTxtFld;
    private javax.swing.JButton billBackBtn;
    private javax.swing.JLabel billBrandLbl;
    private javax.swing.JTextField billBrandTxtFld;
    private javax.swing.JButton billClearBtn;
    private javax.swing.JButton billGenBtn;
    private javax.swing.JLabel billLbl;
    private javax.swing.JLabel billModelLbl;
    private javax.swing.JTextField billModelTxtFld;
    private javax.swing.JLabel billPriceLbl;
    private javax.swing.JTextField billPriceTxtFld;
    private javax.swing.JLabel billQtyLbl;
    private javax.swing.JScrollPane billScrollPane;
    private javax.swing.JTextArea billTextArea;
    private javax.swing.JButton billclearBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JSpinner qtySpin;
    // End of variables declaration//GEN-END:variables

    private void billTextArea(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
